// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jygaxgukrvshvjsorzhi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp5Z2F4Z3VrcnZzaHZqc29yemhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzOTkzMzYsImV4cCI6MjA2ODk3NTMzNn0.2Mw0lnUBWsTNpQeShkYkYtoIAJl-Fn2jTxPPNY6wGSE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});